version: "3.5"
services:
  backend_gateway:
    build: .
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    ports:
      - 5000:5000
    environment: 
      USERS_HOST: backend_user
      USERS_PORT: 5000
      COMPLAINTS_HOST: backend_complaint
      COMPLAINTS_PORT: 5000
      REPORTS_HOST: backend_reports
      REPORTS_PORT: 5000
    networks: 
      - gateway

networks:
  gateway:
    name: gateway